# Generated by Django 5.2.5 on 2026-01-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_offer_seller'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='main.offer'),
        ),
    ]
