# Generated by Django 5.2.5 on 2026-03-09 19:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_brand', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_version', models.CharField(blank=True, max_length=150, null=True)),
                ('vehicle_generation', models.CharField(blank=True, max_length=150, null=True)),
                ('production_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1920), django.core.validators.MaxValueValidator(2026)])),
                ('mileage_km', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('power_hp', models.IntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(2000)])),
                ('displacement_cm3', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000)])),
                ('fuel_type', models.CharField(choices=[('Gasoline', 'Benzyna'), ('Diesel', 'Diesel'), ('Gasoline + LPG', 'Benzyna + LPG'), ('Hybrid', 'Hybryda'), ('Electric', 'Elektryczny'), ('Gasoline + CNG', 'Benzyna + CNG')], max_length=50)),
                ('co2_emissions', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('drive', models.CharField(blank=True, choices=[('Front wheels', 'Napęd przedni'), ('4x4 (permanent)', '4x4 stały'), ('4x4 (attached automatically)', '4x4 automatyczny'), ('Rear wheels', 'Napęd tylny'), ('4x4 (attached manually)', '4x4 manualny')], max_length=50, null=True)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatyczna'), ('Manual', 'Manualna')], max_length=50)),
                ('type', models.CharField(blank=True, choices=[('SUV', 'SUV'), ('compact', 'Kompakt'), ('minivan', 'Minivan'), ('city_cars', 'Samochód miejski'), ('station_wagon', 'Kombi'), ('sedan', 'Sedan'), ('small_cars', 'Małe samochody'), ('coupe', 'Coupe'), ('convertible', 'Kabriolet')], max_length=50, null=True)),
                ('doors_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('colour', models.CharField(blank=True, choices=[('gray', 'Szary'), ('black', 'Czarny'), ('white', 'Biały'), ('red', 'Czerwony'), ('silver', 'Srebrny'), ('blue', 'Niebieski'), ('green', 'Zielony'), ('beige', 'Beżowy'), ('burgundy', 'Bordowy'), ('other', 'Inny'), ('brown', 'Brązowy'), ('golden', 'Złoty'), ('yellow', 'Żółty'), ('violet', 'Fioletowy')], max_length=50, null=True)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('condition', models.CharField(choices=[('New', 'Nowy'), ('Used', 'Używany')], max_length=100)),
                ('features', models.ManyToManyField(blank=True, related_name='cars', to='main.feature')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_offers/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('if_sold', models.BooleanField(default=False)),
                ('offer_end_date', models.DateTimeField(blank=True, null=True)),
                ('offer_publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(choices=[('DS', 'Dolnośląskie'), ('KP', 'Kujawsko-pomorskie'), ('LU', 'Lubelskie'), ('LB', 'Lubuskie'), ('LD', 'Łódzkie'), ('MA', 'Małopolskie'), ('MZ', 'Mazowieckie'), ('OP', 'Opolskie'), ('PK', 'Podkarpackie'), ('PD', 'Podlaskie'), ('PM', 'Pomorskie'), ('SL', 'Śląskie'), ('SK', 'Świętokrzyskie'), ('WM', 'Warmińsko-mazurskie'), ('WP', 'Wielkopolskie'), ('ZP', 'Zachodniopomorskie')], max_length=2)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='main.car')),
            ],
        ),
    ]
