# Generated by Django 5.2.5 on 2025-12-22 20:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_offers/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('if_sold', models.BooleanField(default=False)),
                ('offer_end_date', models.DateTimeField(blank=True, null=True)),
                ('offer_publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_brand', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_version', models.CharField(blank=True, max_length=150, null=True)),
                ('vehicle_generation', models.CharField(blank=True, max_length=150, null=True)),
                ('production_year', models.IntegerField()),
                ('mileage_km', models.FloatField()),
                ('power_hp', models.FloatField(blank=True, null=True)),
                ('displacement_cm3', models.FloatField(blank=True, null=True)),
                ('fuel_type', models.CharField(max_length=50)),
                ('co2_emissions', models.FloatField(blank=True, null=True)),
                ('drive', models.CharField(blank=True, max_length=50, null=True)),
                ('transmission', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('doors_number', models.IntegerField(blank=True, null=True)),
                ('colour', models.CharField(blank=True, max_length=50, null=True)),
                ('origin_country', models.CharField(blank=True, max_length=100, null=True)),
                ('first_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('first_registration_date', models.DateField(blank=True, null=True)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('condition', models.CharField(max_length=100)),
                ('features', models.ManyToManyField(blank=True, related_name='cars', to='main.feature')),
            ],
        ),
    ]
