# Generated by Django 5.2.5 on 2025-09-03 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_version', models.CharField(blank=True, max_length=150, null=True)),
                ('vehicle_generation', models.CharField(blank=True, max_length=150, null=True)),
                ('production_year', models.IntegerField(blank=True, null=True)),
                ('mileage_km', models.FloatField(blank=True, null=True)),
                ('power_hp', models.FloatField(blank=True, null=True)),
                ('displacement_cm3', models.FloatField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('co2_emissions', models.FloatField(blank=True, null=True)),
                ('drive', models.CharField(blank=True, max_length=50, null=True)),
                ('transmission', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('doors_number', models.IntegerField(blank=True, null=True)),
                ('colour', models.CharField(blank=True, max_length=50, null=True)),
                ('origin_country', models.CharField(blank=True, max_length=100, null=True)),
                ('first_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('first_registration_date', models.DateField(blank=True, null=True)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('condition', models.CharField(blank=True, max_length=100, null=True)),
                ('features', models.ManyToManyField(blank=True, related_name='cars', to='main.feature')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('active', models.BooleanField(default=True)),
                ('if_sold', models.BooleanField(default=False)),
                ('offer_end_date', models.DateTimeField(blank=True, null=True)),
                ('offer_publication_date', models.DateTimeField(blank=True, null=True)),
                ('offer_location', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_bought', to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='main.car')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_sold', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
