# Generated by Django 5.2.5 on 2025-09-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='source_index',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
