# Generated by Django 5.2.5 on 2025-12-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='first_owner',
        ),
        migrations.RemoveField(
            model_name='car',
            name='first_registration_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='origin_country',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='updated_at',
        ),
    ]
