# Generated by Django 5.2.5 on 2025-12-30 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_car_first_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='co2_emissions',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='displacement_cm3',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage_km',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='power_hp',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='production_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1920)]),
        ),
    ]
