# Generated by Django 5.2.5 on 2026-01-02 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_car_co2_emissions_alter_car_displacement_cm3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='production_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1920), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
